project_name: "Gaussian_SLAM_ros_realsense"
ros_stream: True
dataset_name: "ros_live"
checkpoint_path: null
use_wandb: False
frame_limit: -1 # for debugging, set to -1 to disable
seed: 0
data:
  scene_name: scene0
  input_path: data/ros_live/scene0/
  output_path: output/ros_live/scene0/ 
mapping:
  ros_stream: True
  new_submap_every: 50
  map_every: 1
  iterations: 100
  new_submap_iterations: 100
  new_submap_points_num: 100000 
  new_submap_gradient_points_num: 50000 
  new_frame_sample_size: 30000 
  new_points_radius: 0.0001
  current_view_opt_iterations: 0.4 # What portion of iterations to spend on the current view
  alpha_thre: 0.6
  pruning_thre: 0.5
  submap_using_motion_heuristic: True
camera: 
  manip_cam:
    rgb_topic: '/camera/color/image_raw'
    depth_topic: '/camera/aligned_depth_to_color/image_raw'
    rgb_info_topic: '/camera/color/camera_info'
    depth_info_topic: '/camera/aligned_depth_to_color/camera_info'
    ref_frame: 'world'
    camera_frame: 'camera_color_optical_frame'

tracking:
  ros_stream: True
  gt_camera: False
  w_color_loss: 0.6
  iterations: 200
  cam_rot_lr: 0.002
  cam_trans_lr: 0.01
  odometry_type: "const_speed"  # gt, const_speed, odometer
  help_camera_initialization: False # temp option to help const_init
  init_err_ratio: 5
  odometer_method: "hybrid" # hybrid or point_to_plane
  filter_alpha: False
  filter_outlier_depth: False
  alpha_thre: 0.98
  soft_alpha: True
  mask_invalid_depth: True
cam: 
  H: 360 
  W: 640
  fx: 453.10504150390625
  fy: 452.6966857910156
  cx: 318.85125732421875
  cy: 180.7555694580078
  depth_scale: 1000.
  crop_edge: 12